### PR TITLE
Add mca XmlnsPrefix for http://schemas.microsoft.com/netfx/2009/xaml/…

### LINKED ISSUE #107: Create project and items template
As this project avance we need to easily start a new project using the dotnet CLI or visual studio and also add items to the project. 

This will made easy the day to day development.

### PR DESCRIPTION
**Pull request by danielmeza**
…activities

This will fix #107 and improve compatibility with older projects

### CODE REVIEW

**Comment by danielmeza** [comment]
@lbargaoanu  check this out!

**Comment by lbargaoanu** [comment]
Look at the tests. The workflows run just fine.

**Comment by danielmeza** [comment]
I can't see the settings since the pr is closed

**Comment by danielmeza** [comment]
Ok, sorry I missing that XmlnsCompatibleWith solve the problem case expose the .dll as provider for that assembly

**Pull request closed without merging**
